database:
  host: "192.168.1.242"
  port: 3306
  name: "wafelz"
  username: "luckperms"
  password: ""

server:
  lobby: false
  oneblock: false
  fbf: false
  discord-link: https://discord.gg/tnbZZEQjAP

broadcasts:
  - "<blue>Join our Discord: <click:open_url:'https://discord.gg/tnbZZEQjAP'><underline>Click Here</underline></click>"
  - "<click:run_command:'/vote'><gold>Remember to vote daily for rewards! /vote</gold></click>"
  - "<green>Need help? Ask staff anytime!</green>"
  - "<click:run_command:'/buy'><aqua>Please consider donating to help support the server!</aqua></click>"

gui:
  title: "Chat Colors"
  size: 36

gui2:
  title: "Mode Selector"
  size: 27

suffixes:
  legend:
    suffix: " Â§5[LEGEND]"
    display-name: "Â§5Legend Suffix"
    permission: "suffix.legend"
    material: "NETHERITE_INGOT"

  heart:
    suffix: " Â§câ¤"
    display-name: "Â§cHeart Suffix"
    permission: "suffix.heart"
    material: "RED_DYE"

  star:
    suffix: " Â§eâ­"
    display-name: "Â§eStar Suffix"
    permission: "suffix.star"
    material: "NETHER_STAR"

  fire:
    suffix: " Â§eğŸ”¥"
    display-name: "Â§eFire Suffix"
    permission: "suffix.fire"
    material: "BLAZE_POWDER"
  ee:
    suffix: " Â§7ğŸ”¥"
    display-name: "Â§aEaster egg suffix"
    permission: "suffix.ee"
    material: "SNIFFER_EGG"
  money:
    suffix: " Â§6$"
    display-name: "Â§6Donator suffix. Purchase something on the server store to unlock!"
    permission: "suffix.donator"
    material: "GOLD_INGOT"
  diasword:
    suffix: " Â§bğŸ—¡"
    display-name: "Â§aDiamond sword suffix"
    permission: "suffix.diasword"
    material: "DIAMOND_SWORD"
  goldsword:
    suffix: " Â§6ğŸ—¡"
    display-name: "Â§aGold sword suffix"
    permission: "suffix.goldsword"
    material: "GOLDEN_SWORD"
  ironsword:
    suffix: " Â§7ğŸ—¡"
    display-name: "Â§aIron sword suffix"
    permission: "suffix.ironsword"
    material: "IRON_SWORD"
  stonesword:
    suffix: " Â§8ğŸ—¡"
    display-name: "Â§aStone sword suffix"
    permission: "suffix.stonesword"
    material: "STONE_SWORD"
  bow:
    suffix: " Â§6ğŸ¹"
    display-name: "Â§aBow suffix"
    permission: "suffix.bow"
    material: "BOW"
  diaaxe:
    suffix: " Â§bğŸª“"
    display-name: "Â§aDiamond axe suffix"
    permission: "suffix.diaaxe"
    material: "DIAMOND_AXE"
  trident:
    suffix: " Â§bğŸ”±"
    display-name: "Â§aTrident suffix"
    permission: "suffix.trident"
    material: "TRIDENT"
  ironaxe:
    suffix: " Â§7ğŸª“"
    display-name: "Â§aIron sword suffix"
    permission: "suffix.ironaxe"
    material: "IRON_AXE"
  goldaxe:
    suffix: " Â§6ğŸª“"
    display-name: "Â§aGolden axe suffix"
    permission: "suffix.goldaxe"
    material: "GOLDEN_AXE"
  stoneaxe:
    suffix: " Â§8ğŸª“"
    display-name: "Â§aStone axe suffix"
    permission: "suffix.stoneaxe"
    material: "STONE_AXE"
  fishingrod:
    suffix: " Â§3ğŸ£"
    display-name: "Â§aFishing rod suffix"
    permission: "suffix.fishing_rod"
    material: "FISHING_ROD"
  potion:
    suffix: " Â§9ğŸ§ª"
    display-name: "Â§aPotion suffix"
    permission: "suffix.potion"
    material: "POTION"
  splshpotion:
    suffix: " Â§9âš—"
    display-name: "Â§aSplash potion suffix"
    permission: "suffix.splshpotion"
    material: "SPLASH_POTION"